#!/usr/bin/env bash
# Ce script ping une adresse IP spécifiée en argument 5 fois et affiche les résultats.

if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ping -c 5 "$1"
